# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

workspace 'ZWallet'

target 'App' do

end

target 'Core' do
  project '../Module/Core/Core'

end

target 'Login' do
  project '../Module/Login/Login'

end

target 'Home' do
  project '../Module/Home/Home'

end